#!/usr/bin/env sh
input=""
output=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    -o)
      output="$2"
      shift 2
      ;;
    -*)
      shift
      ;;
    *)
      if [ -f "$1" ]; then
        input="$1"
      fi
      shift
      ;;
  esac
done

if [ -n "$input" ] && [ -n "$output" ]; then
  cp "$input" "$output"
fi
